apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    cnrm.cloud.google.com/operator-version: {{ .Values.gccOperatorVersion }}
  labels:
    cnrm.cloud.google.com/operator-system: "true"
  name: configconnector-operator-cnrm-viewer-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configconnector-operator-cnrm-viewer
subjects:
- kind: ServiceAccount
  name: configconnector-operator
  namespace: configconnector-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    cnrm.cloud.google.com/operator-version: {{ .Values.gccOperatorVersion }}
  labels:
    cnrm.cloud.google.com/operator-system: "true"
  name: configconnector-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configconnector-operator-manager-role
subjects:
- kind: ServiceAccount
  name: configconnector-operator
  namespace: configconnector-operator-system
