apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/operator-version: {{ .Values.gccOperatorVersion }}
  labels:
    cnrm.cloud.google.com/operator-system: "true"
  name: configconnector-operator-system
